### ISSUE TITLE
Versioned release?

### ISSUE THREAD

**Issue by cat-marin** [OverMighty/i-use-arch-btw#3]
Hey there! I was hoping you could provide a versioned tarball in the github releases so that it can be packaged on distros like Void Linux. Thanks!

**Comment by OverMighty** [comment]
I'll see if there's anything I can polish a bit and then I'll probably release version 1.0.0.

**Comment by OverMighty** [comment]
Looking at this project for the first time in a while, I found quite a few things to improve. I'll work on it.

**Comment by OverMighty** [comment]
Don't worry, I'll come back from the dead soon.

**Comment by OverMighty** [comment]
Ok, I'll finish this tomorrow.

**Comment by OverMighty** [comment]
Ok, tomorrow I'll do it for real this time.

**Comment by cat-marin** [comment]
> Ok, tomorrow I'll do it for real this time.

👀

**Comment by OverMighty** [comment]
Ok, I'll do it this evening when I come back from school for sure. Sorry, I have serious procrastination problems.

**Comment by cat-marin** [comment]
> Ok, I'll do it this evening when I come back from school for sure. Sorry, I have serious procrastination problems.

👀👀

**Comment by OverMighty** [comment]
Alright, I'll give you a more realistic deadline: Wednesday, January 6, 2020 @ 22:00 UTC+1. If it's not done by then, I owe you $5.

**Comment by OverMighty** [comment]
I decided to rewrite the whole thing but I don't have the time right now, so here's the official release of version 0.1.0 instead of 1.0.0: https://github.com/OverMighty/i-use-arch-btw/releases/tag/0.1.0

**Comment by OverMighty** [comment]
I can't believe I made you wait 2 months for this.

**Comment by cat-marin** [comment]
Just noticed he did it lol, closing

**Comment by Alvarito050506** [comment]
> Alright, I'll give you a more realistic deadline: Wednesday, January 6, _**2020**_ @ 22:00 UTC+1. If it's not done by then, I owe you $5.

So, you owe $5.

**Comment by OverMighty** [comment]
I had typed 2021. A cosmic ray probably flipped a bit in my laptop's RAM.

**Comment by Alvarito050506** [comment]
That's a myth, I bet they were [butterflies](https://xkcd.com/378/).

**Comment by Alvarito050506** [comment]
That's a myth, I bet they were [butterflies](https://xkcd.com/378/).
