### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by JustRed23** [overmighty/i-use-arch-btw#8]
Like okay, yes i use arch but don't do me like this ;-;

**Comment by JustRed23** [comment]
Flex on people like neofetch does ofc
(Or just print version information or smth haha)

**Comment by baris-inandi** [comment]
i use arch btw

**Comment by overmighty** [comment]
Should I try implementing a JIT compiler for x86_64?

**Comment by baris-inandi** [comment]
> Should I try implementing a JIT compiler for x86_64?

Yes. @overmighty it has to be done.

**Comment by Froggo8311** [comment]
neofetch command? maybe print to stdout

**Comment by JustRed23** [comment]
> neofetch command? maybe print to stdout
Yes.

**Comment by overmighty** [comment]
> neofetch command? maybe print to stdout

`btw` already prints the current value as character to stdout. What would `neofetch` do exactly?

**Comment by JustRed23** [comment]
What if neofetch generates a random character

**Comment by Froggo8311** [comment]
Or perhaps get/set system information and settings?

**Comment by overmighty** [comment]
> Should I try implementing a JIT compiler for x86_64?

I finally have time to work on this since I am now on summer vacation, but I need a couple days of rest. I didn't know my first year as a computer science student would suck so much.

**Comment by overmighty** [comment]
Ok I just rewrote the entire project for the second time so I'm going to work on the JIT compile now for real this time.

**Comment by overmighty** [comment]
> Should I try implementing a JIT compiler for x86_64?

Done.
